const Categories = [
  {
    id: 1,
    title: "Amazon Bip Home",
    price: 370,
    image: "./Image/BipHome.png",
    category: "Software",
  },
  {
    id: 2,
    title: "Amazon Boze Headphones",
    price: 370,
    image: "./Image/BoseHeadphones.png",
    category: "Electronic",
  },
  {
    id: 3,
    title: "Kanken Bag",
    price: 370,
    image: "./Image/bag.png",
    category: "Sport",
  },
  {
    id: 4,
    title: "Spine Chair",
    price: 370,
    image: "./Image/chair.png",
    category: "Furniture",
  },
  {
    id: 5,
    title: "Vases",
    price: 370,
    image: "./Image/Vases.png",
    category: "Furniture",
  },
  {
    id: 6,
    title: "Yoga Mat",
    price: 370,
    image: "./Image/YogaMat.png",
    category: "Sport",
  },
  {
    id: 7,
    title: "Apple TV",
    price: 370,
    image:
      "./Image/apple-tv-png-apple-tv-4k-png-transparent.png",
    category: "Software",
  },
  {
    id: 8,
    title: "Ferrero",
    price: 370,
    image: "./Image/Ferrero.jpg",
  },
  {
    id: 9,
    title: "Food & Grossery",
    price: 370,
    image:
      "./Image/Food & Grossery2.jpg",
    category: "Food",
  },
  {
    id: 10,
    title: "Hard Drive",
    price: 370,
    image: "./Image/Hard-drive.jpeg",
    category: "",
  },
  {
    id: 11,
    title: "Macaron",
    price: 370,
    image: "./Image/macarona.jpeg",
    category: "Food",
  },

  {
    id: 13,
    title: "Sport Shoes",
    price: 370,
    image:
      "./Image/Sport-shoes-green.png",
    category: "Sport",
  },
  {
    id: 14,
    title: "Sport Shoes",
    price: 370,
    image: "./Image/Sport-shoes.png",
    category: "Sport",
  },
  {
    id: 15,
    title: "Kettle",
    price: 370,
    image: "./Image/kettle.png",
    category: "Furniture",
  },
  {
    id: 16,
    title: "laptop",
    price: 370,
    image: "./Image/laptop.png",
    category: "Electronic",
  },
  {
    id: 17,
    title: "Mobile",
    price: 370,
    image: "./Image/mobile.png",
    category: "Electronic",
  },
  {
    id: 18,
    title: "Shoes",
    price: 370,
    image: "./Image/shoes.png",
    category: "Sport",
  },
  {
    id: 19,
    title: "Shoes",
    price: 370,
    image: "./Image/shoesnike.png",
    category: "Sport",
  },
  {
    id: 20,
    title: "TV",
    price: 370,
    image: "./Image/tv.png",
    category: "Electronic",
  },
];

export default Categories;
